# Generated by Django 2.1.7 on 2019-03-10 16:57

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [CreateExtension("timescaledb")]
