# Generated by Django 2.1.7 on 2019-03-10 22:07

import backend.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [("backend", "0001_make_extension")]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "name",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("default", models.BooleanField(default=False)),
            ],
            options={"db_table": "telemetry_dbs"},
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "metric_name",
                    models.CharField(
                        blank=True, db_index=True, default="'", max_length=64
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        default=backend.models._get_default_db,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.Database",
                    ),
                ),
            ],
            options={"db_table": "telemetry"},
        ),
        migrations.AlterUniqueTogether(
            name="telemetry",
            unique_together={("database", "time", "metric_name", "tags")},
        ),
    ]
