# Generated by Django 2.1.7 on 2019-03-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("backend", "0002_database_telemetry")]

    operations = [migrations.RunSQL("SELECT create_hypertable('telemetry', 'time')")]
